backend:
  name: github
  repo: anselmoavaga/Don
  branch: main
  auth_scope: repo

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projets"
    label: "Projets"
    files:
      - file: "_data/projets.json"
        label: "Liste des projets"
        name: "projets"
        fields:
          - label: "Projets"
            name: "projets"
            widget: "list"
            fields:
              - { label: "Titre", name: "titre", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
