backend:
  name: github
  repo: anselmoavaga/Don
  branch: main
  auth_scope: repo

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projets"
    label: "Projets"
    files:
      - file: "_data/projets.json"
        label: "Liste des projets"
        name: "projets"
        fields:
          - label: "Projets"
            name: "projets"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Titre", name: "titre", widget: "string"}
              - {label: "Date", name: "date", widget: "string"}
              - {label: "Cat", name: "cat", widget: "select", options: ["education", "sante", "environnement", "social"]}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Images"
                name: "images"
                widget: "list"
                field: {label: "Image", name: "url", widget: "image"}

  - name: "galerie"
    label: "Galerie"
    files:
      - file: "_data/galerie.json"
        label: "Galerie"
        name: "galerie"
        fields:
          - label: "Images"
            name: "galerie"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Image", name: "url", widget: "image"}
              - {label: "Legende", name: "legende", widget: "string"}

  - name: "membres"
    label: "Membres"
    files:
      - file: "_data/membres.json"
        label: "Equipe"
        name: "membres"
        fields:
          - label: "Membres"
            name: "membres"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Nom", name: "nom", widget: "string"}
              - {label: "Fonction", name: "fonction", widget: "string"}
              - {label: "Email", name: "email", widget: "string", required: false}
              - {label: "Tel", name: "tel", widget: "string", required: false}
              - {label: "Photo", name: "photo", widget: "image"}

  - name: "temoignages"
    label: "Temoignages"
    files:
      - file: "_data/temoignages.json"
        label: "Temoignages"
        name: "temoignages"
        fields:
          - label: "Temoignages"
            name: "temoignages"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Nom", name: "nom", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Texte", name: "texte", widget: "text"}
              - {label: "Photo", name: "photo", widget: "image"}